### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'approvesMethodFor')

### ISSUE THREAD

**Issue by matgnt** [interop-alliance/did-web-resolver#14]
I'm trying to run the example from the Readme:
```
import { Ed25519VerificationKey2020 }
  from '@digitalbazaar/ed25519-verification-key-2020'
import { X25519KeyAgreementKey2020 }
  from '@digitalbazaar/x25519-key-agreement-key-2020'
import { CryptoLD } from 'crypto-ld'

import * as didWeb from '@interop/did-web-resolver' // causes the error

const cryptoLd = new CryptoLD()
cryptoLd.use(Ed25519VerificationKey2020)
cryptoLd.use(X25519KeyAgreementKey2020)

const didWebDriver = didWeb.driver({ cryptoLd })
```

The `did-web-resolver` import causes the error:
`TypeError: Cannot read properties of undefined (reading 'approvesMethodFor')`

I tried different versions (2.0.0, 1.1.0, latest head).

Any ideas what might cause this error?

**Comment by dmitrizagidulin** [comment]
@matgnt - I think I know the cause. I'm in the process of converting this library to support TypeScript; that should fix it. (Should be ready later today.)

**Comment by matgnt** [comment]
Sounds good @dmitrizagidulin 
Let me know if I can test a pre-release / development branch with your changes.
Thanks,
Matthias

**Comment by matgnt** [comment]
Short update for everyone who needs a workaround:

Disclaimer: I'm using NuxtJS stack and there is a lot of "magic" going on in the background (webpack and more) that I do not fully understand - but hey, that's the benefit of such a stack, right ;-)

So I figured out that my stack picked things twice and some didn't work well and those parts came from the `esm` directories of the `did-web-resolver`. So what did I do? Just delete them:

```
./node_modules/@interop/did-web-resolver/dist/esm
./node_modules/@interop/did-web-resolver/node_modules/did-io/dist/esm
./node_modules/@interop/did-web-resolver/node_modules/lru-memoize/dist/esm
```

In addition to the error message above, you could see the same message for `driver` and `lruCache`.
As I said, after deleting the 3 `esm` directories it worked for me with the demo code from the Readme file (using the NuxtJS stack).

If someone knows a better way how to exclude those `esm` directories - maybe via a webpack rule, please let me know :-)

**Comment by dmitrizagidulin** [comment]
@matgnt - nice! thanks.
(Yeah, I'm working on getting rid of that `esm` dependency, for this exact reason.)

**Comment by dmitrizagidulin** [comment]
@matgnt - Can you test if PR https://github.com/interop-alliance/did-web-resolver/pull/15 addresses that error?

**Comment by matgnt** [comment]
@dmitrizagidulin actually I'm still having problems with it. As I understand, the following is happening now:

There is no subdirectory `node_modules` with the dependencies in the package anymore.
It now pulls in content from:
`./node_modules/@digitalcredentials/`
which still contains `esm` content which fails - at least in my stack (NuxtJS)
I guess that those packages also need an update to not contain that directory anymore.
Interestingly, the `did-web-resolver` still contains an `esm` directory. Is that on purpose?

Now I have to delete the following 3 directories to get it working - 2 of them in different locations now:
```
./node_modules/@digitalcredentials/lru-memoize/dist/esm
./node_modules/@digitalcredentials/did-io/dist/esm

./node_modules/@interop/did-web-resolver/dist/esm
```

As I said earlier, it might be still a problem on my side with NuxtJS configuration - even though, I'm using more or less default configuration here... :-)

**Comment by dmitrizagidulin** [comment]
@matgnt - thanks!
Investigating...

**Comment by dmitrizagidulin** [comment]
@matgnt - ah, ok. So,  there's two different things with the name `esm`.

The thing that I was getting rid of, was the runtime use of the [`esm` transpiler](https://www.npmjs.com/package/esm). (This is the reason that Digital Bazaar's packages don't work with TypeScript / ReactNative).

So now, _instead_ of runtime transpiling, did-web-resolver (and all `@digitalcredentials` libraries) transpile to ESM at BUILD time. (So that's what that `/dist/esm` directory is for). So, that part is intended, and should be working.

Can you paste the details of the error you're seeing?

**Comment by matgnt** [comment]
First error I hit is regarding LruCache, but it's the same for the other mentioned packages (`driver` in the web-resolver package):
```
client.js?06a0:102 TypeError: Cannot read properties of undefined (reading 'LruCache')
    at eval (index.js?2036:2:1)
    at Module../node_modules/@digitalcredentials/lru-memoize/dist/esm/index.js (identity.js:263:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (CachedResolver.js?4856:6:1)
    at Object../node_modules/@digitalcredentials/did-io/dist/CachedResolver.js (identity.js:167:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (index.js?d028:6:1)
    at Object../node_modules/@digitalcredentials/did-io/dist/index.js (identity.js:215:1)
_callee$ @ client.js?06a0:102

```

Adding a debugger to the file
`./node_modules/@digitalcredentials/lru-memoize/dist/esm/index.js`
I can see that 
```
import cjsModule from '../index.js';
debugger
export const LruCache = cjsModule.LruCache;
```
`cjsModule` is undefined. So I guess it could be also a problem with my stack here (NuxtJS and/or Webpack...)
Any ideas?

**Comment by dmitrizagidulin** [comment]
@matgnt - thanks. And can you show me the code where you're importing the driver? (I'd like to see if you're writing typescript, or ESM node.js, etc.)

**Comment by matgnt** [comment]
```
<script>
import { Ed25519VerificationKey2020 }
  from '@digitalbazaar/ed25519-verification-key-2020'
import { X25519KeyAgreementKey2020 }
  from '@digitalbazaar/x25519-key-agreement-key-2020'
import { CryptoLD } from 'crypto-ld'

import * as didWeb from '@interop/did-web-resolver'

const cryptoLd = new CryptoLD()
cryptoLd.use(Ed25519VerificationKey2020)
cryptoLd.use(X25519KeyAgreementKey2020)

const didWebDriver = didWeb.driver({ cryptoLd })

const DEFAULT_KEY_MAP = {
  // capabilityInvocation: 'Ed25519VerificationKey2020',
  authentication: 'Ed25519VerificationKey2020',
  assertionMethod: 'Ed25519VerificationKey2020'
  // capabilityDelegation: 'Ed25519VerificationKey2020',
  // keyAgreement: 'X25519KeyAgreementKey2020'
}
```

and then in another place I do:
```
      const url = 'https://sub.domain.com'
      const { didDocument, keyPairs } = await didWebDriver.generate({ url, keyMap: DEFAULT_KEY_MAP })
```

So it's in the browser, not (!) nodejs backend. NuxtJs does "the magic" ;-) (transpiler...)

**Comment by matgnt** [comment]
Ok, I now found a better workaround. Instead of deleting the `esm` folder, you can do this in your `nuxt.config.js`
(for version 2.1.1 that uses the "digitalcredentials" dependencies)
```
  alias: {
    '@interop/did-web-resolver': '/node_modules/@interop/did-web-resolver/dist/index.js',
    '@digitalcredentials/did-io': '/node_modules/@digitalcredentials/did-io/dist/index.js',
    '@digitalcredentials/lru-memoize': '/node_modules/@digitalcredentials/lru-memoize/dist/index.js'
  },

```
It explicitly tells the system which files to pick for which import.
If you're using another stack (not NuxtJS) that uses webpack and you encouter similar problems, you can do the same with webpack config under `resolve.alias`

I'm closing the issue now, since it seems it is a special case with my stack and I found a workaround for it. If someone runs into the same problem, we might reopen in case it's a more general problem.

Thanks @dmitrizagidulin  for your support!
